Ghc 8.8.1
kowainik/hakyll-shortcut-links pull request #18
Opened 2019-10-01 16:58 UTC by SanchayanMaity

Implements #16

2019-10-01 18:33 UTC, chshersh requested changes
Looks like you also need to bump up `base` version in the `.cabal` file. Otherwise looks good :+1:

2019-10-02 06:27 UTC, SanchayanMaity commented
> Looks like you also need to bump up `base` version in the `.cabal` file. Otherwise looks good +1

Seems like bumping to 4.14 conflicts with haddock.

2019-10-02 06:57 UTC, chshersh commented
@SanchayanMaity, yes, latest `pandoc` depends on `haddock-library-1.7` which doesn't support GHC-8.8. There's `haddock-library-1.8` which supports GHC-8.8, so we need to wait until `pandoc` updates its dependencies. Can take a while...

2019-10-02 07:00 UTC, SanchayanMaity commented
@chshersh Understood. Will keep an eye out for the update.

2019-12-16 14:34 UTC, chshersh commented
@SanchayanMaity I think you also should update `base` version in the `.cabal` file to enable `ghc-8.8.1`.

2019-12-16 14:35 UTC, chshersh commented on hakyll-shortcut-links.cabal
> +    ghc-options:       -Wmissing-deriving-strategies
Let's error on missing deriving strategies, not just warn:

https://github.com/kowainik/tomland/blob/d9b7a1dc344e41466788fe00d0ea016f04629ade/tomland.cabal#L58-L60

2020-02-28 20:03 UTC, vrom911 commented
Hey @SanchayanMaity ! 
I went ahead and finished the issue in #22. Thank for your work on this again!

2020-02-28 20:03 UTC, closed without merging